### ISSUE TITLE
Config File

### ISSUE THREAD

**Issue by anazhd** [rohitm/siena#1]
Hi, I tried to run this but first of all, I couldn't find any config file or config section so I figured, I'm missing something here. I'm totally not sure, can you help me out?

**Comment by rohitm** [comment]
@anazhd - Hey there, so the reason I didn't commit my configuration file is that everybody will have their own different local settings. I'll commit the file shortly.

**Comment by rohitm** [comment]
@anazhd - I've committed it. However, I still haven't put together a rules engine or actually tested if the strategy works with live data. It is still a work in progress. Now for, I'm able to cache 24 hours of trade history from bittrex into redis. I'm also able to calculate the moving averages live. If you wish to contribute to this project - I'm looking for help on the best trading strategy to use with cryptocurrencies. The simple moving average formula is a very basic strategy.
