### ISSUE TITLE
Index.js:5643 - SyntaxError: Unexpected token (

### ISSUE THREAD

**Issue by mjwowpa** [rohitm/siena#2]
Hi,

When launching siena with forever, i have this problem:
Log:

`data:    src/index.js:5643 - /Users/Capriccio/Downloads/siena-master/src/index.js:106
data:    src/index.js:5643 - const getMarketTrend = async (movingAverageShort, movingAverageMid, movingAverageLong) => {
data:    src/index.js:5643 -                              ^
data:    src/index.js:5643 - SyntaxError: Unexpected token (
data:    src/index.js:5643 -     at createScript (vm.js:56:10)
data:    src/index.js:5643 -     at Object.runInThisContext (vm.js:97:10)
data:    src/index.js:5643 -     at Module._compile (module.js:542:28)
data:    src/index.js:5643 -     at Object.Module._extensions..js (module.js:579:10)
data:    src/index.js:5643 -     at Module.load (module.js:487:32)
data:    src/index.js:5643 -     at tryModuleLoad (module.js:446:12)
data:    src/index.js:5643 -     at Function.Module._load (module.js:438:3)
data:    src/index.js:5643 -     at Module.runMain (module.js:604:10)
data:    src/index.js:5643 -     at run (bootstrap_node.js:383:7)
data:    src/index.js:5643 -     at startup (bootstrap_node.js:149:9)
data:    src/index.js:5643 - error: Forever detected script exited with code: 1
data:    src/index.js:5643 - error: Script restart attempt #1
data:    src/index.js:5643 - /Users/Capriccio/Downloads/siena-master/src/index.js:106
data:    src/index.js:5643 - const getMarketTrend = async (movingAverageShort, movingAverageMid, movingAverageLong) => {
`
Any idea ? :)

**Comment by rohitm** [comment]
Which version of node are you using ? This requires the latest stable version that supports ECMA6 features like async / await.

**Comment by mjwowpa** [comment]
On OSX
Node:v6.11.4
Npm: 3.10.10

**Comment by rohitm** [comment]
Upgrade to Node:v8.6.0

Also, You'll need to setup your private keys from bittrex. I'm still working on refining the algorithm though so don't trade big money.

**Comment by rohitm** [comment]
I can use this thread to help you setup this project from scratch if you like. Because, I haven't put together the documentation or installation instructions. You'll need redis, move some money into your bittrex account, setup the cache server first, etc.

**Comment by mjwowpa** [comment]
I will try.
Settings with Bittrex API is alrady done.
You want to upgrade the algorithm with trader rules or all the approach (BB etc..)?

**Comment by rohitm** [comment]
Upgrade rules ? I'm not quite sure I follow your question.

**Comment by mjwowpa** [comment]
Yeah it's a little confuse when you don't know forever etc.. to install & start the project.

**Comment by mjwowpa** [comment]
Oh upgrading you algorithm with trading _rules_.

**Comment by rohitm** [comment]
Yeah I know, I haven't made a proper installation / setup guide, I'll do it soon! 😞 . But feel free to fork over and change up the trading strategy. If it works better than my solution, I can merge it back.

**Comment by mjwowpa** [comment]
In fact there is two main approachs: Scalping and Bollinger Bands.
If I understand, you choose the Scalping approach with ping-pong effect. It's quite good but we have to test the strategy impact to know if it's viable.

**Comment by rohitm** [comment]
I've used a version of this : http://www.investopedia.com/articles/active-trading/010116/perfect-moving-averages-day-trading.asp

I'll have to read up on scalping and bollinger (thanks for the tip), I'm currently testing my strategy with about 35 USD sitting in bittrex. I'm going to let it run for a few days to test it's viability.

**Comment by mjwowpa** [comment]
New node version, new error :)
```
forever logs 0
data:    src/index.js:5878 - Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
data:    src/index.js:5878 - Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
data:    src/index.js:5878 - events.js:182
data:    src/index.js:5878 -       throw er; // Unhandled 'error' event
data:    src/index.js:5878 -       ^

```

**Comment by rohitm** [comment]
Yep, so this is where I need to help you setup the project.
1. You'll need to install redis locally - https://redis.io - Thats the database used to cache bittrex data.
2. You'll need to run the cache server first. `$ npm run forever-start-cache`
👆 Let this run for at-least 15 minutes or Ideally 13 hours for the trading algorithm to work correctly.
3. Run siena. `$ npm run siena` 
4. Hopefully get rich

**Comment by rohitm** [comment]
Also make sure that your bittrex account has some etherium in it.

**Comment by mjwowpa** [comment]
Ok 90% !!! Do you thinks i have to type an another option with `$ npm run forever-start-cache` ?
```
forever logs 1
data:    src/market-history-cache.js:6108 - marketHistoryCache: Polling bittrex for history every 15 minutes, cache length = 168 hours
data:    src/market-history-cache.js:6108 - marketHistoryCache: Server started on port 3452
data:    src/market-history-cache.js:6108 - Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
data:    src/market-history-cache.js:6108 - Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
```

**Comment by mjwowpa** [comment]
And last question, what is your OS ?
Because with W10 it's impossible to install dependancies likes _fsevents_

**Comment by rohitm** [comment]
From your logs, it just looks like redis is not running in the background. You shouldn't get `Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379`.

**Comment by rohitm** [comment]
I'm on OSX

**Comment by rohitm** [comment]
Oh yeah, did you perform `$ npm install` ? That should install all your node dependencies. Redis is the only non node dependency.

**Comment by rohitm** [comment]
Try this for redis
https://medium.com/@petehouston/install-and-config-redis-on-mac-os-x-via-homebrew-eb8df9a4f298

**Comment by mjwowpa** [comment]
Yes of course for `npm install`.
My version of redis was installed with homebrew (OSX haha)

**Comment by rohitm** [comment]
If its installed, then you should probably run redis-cli and make sure it works. My code uses the default port and no authentication for redis. Perhaps your local setup is different.

**Comment by mjwowpa** [comment]
Okay fixed..
Install Redis via Homebrew and type `redis-server /usr/local/etc/redis.conf` for setup siena.
After that, `$ npm run forever-start-cache`

**Comment by rohitm** [comment]
Yes, Hopefully this time you didn't get the `Redis connection to 127.0.0.1:6379 failed` message.

**Comment by mjwowpa** [comment]
Nop 👍  With XRP-BTC Config..
```
data:    src/market-history-cache.js:6108 - cacheMarketHistory: 200 transactions cached
data:    src/market-history-cache.js:6108 - cacheMarketHistory, periodInMilliseconds, cacheLowerLimitTimestamp: 604800000, Thu Oct 12 2017 17:44:02 GMT+0200 (CEST)
data:    src/market-history-cache.js:6108 - cacheMarketHistory: Cleaning cache with redis code : 'ZREMRANGEBYSCORE BTC-XRP -inf 1507823042897'
```

**Comment by rohitm** [comment]
Oh wow XRP-BTC eh? Good luck. 👍 Let me know how this project works for you

**Comment by rohitm** [comment]
My values are fine tuned for etherium. You'll need to find the moving average times that work for your currency. Trial and error my friend!

**Comment by mjwowpa** [comment]
Yeah XRP-BTC for the volatility and stability. I will try and I'll say the verdict haha :)

**Comment by rohitm** [comment]
Thanks, And if you find it good. ⭐️ for my project. Thanks.
